/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AboutRouteImport } from './pages/about'
import { Route as IndexRouteImport } from './pages/index'
import { Route as TaskPrioritiesIndexRouteImport } from './pages/task-priorities/index'
import { Route as TaskCategoriesIndexRouteImport } from './pages/task-categories/index'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskPrioritiesIndexRoute = TaskPrioritiesIndexRouteImport.update({
  id: '/task-priorities/',
  path: '/task-priorities/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskCategoriesIndexRoute = TaskCategoriesIndexRouteImport.update({
  id: '/task-categories/',
  path: '/task-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/task-categories': typeof TaskCategoriesIndexRoute
  '/task-priorities': typeof TaskPrioritiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/task-categories': typeof TaskCategoriesIndexRoute
  '/task-priorities': typeof TaskPrioritiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/task-categories/': typeof TaskCategoriesIndexRoute
  '/task-priorities/': typeof TaskPrioritiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/task-categories'
    | '/task-priorities'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/dashboard' | '/task-categories' | '/task-priorities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard/'
    | '/task-categories/'
    | '/task-priorities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  TaskCategoriesIndexRoute: typeof TaskCategoriesIndexRoute
  TaskPrioritiesIndexRoute: typeof TaskPrioritiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-priorities/': {
      id: '/task-priorities/'
      path: '/task-priorities'
      fullPath: '/task-priorities'
      preLoaderRoute: typeof TaskPrioritiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-categories/': {
      id: '/task-categories/'
      path: '/task-categories'
      fullPath: '/task-categories'
      preLoaderRoute: typeof TaskCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  TaskCategoriesIndexRoute: TaskCategoriesIndexRoute,
  TaskPrioritiesIndexRoute: TaskPrioritiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
